version: "3.8"
services:
  uber_postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: uber_eats
    network_mode: bridge
    volumes:
      - postgres:/var/lib/postgresql/data
  uber_pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    network_mode: bridge
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - uber_postgres
  uber_redis:
    image: redis:alpine
    command:
      - redis-server
    ports:
      - "6379:6379"
    container_name: main_Redis
    network_mode: bridge
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
volumes:
  postgres:
  pgadmin-data:
  redis-data:
  redis-conf:
