version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: uber_eats_api
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
       NODE_ENV: production
       POSTGRES_USER: admin
       POSTGRES_PASSWORD: admin
       POSTGRES_DB_NAME: uber_eats
       POSTGRES_DB_HOST: postgres
       POSTGRES_DB_PORT: 5432
    networks:
      uber_network:
    depends_on:
      - uber_postgres
    ports:
      - '3000:3000'
  uber_postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: uber_eats
    networks:
      uber_network:
    volumes:
      - postgres:/var/lib/postgresql/data
  uber_pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      uber_network:
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - uber_postgres
networks:
  uber_network:
    internal: false
    name: uber_network
    driver: bridge
volumes:
  postgres:
  pgadmin-data:
  redis-data:
